---
new_page_extension: md
auto_deploy: false
admin_path:
webhook_url:
sections:
- type: directory
  path: _publications
  label: Publications
  create: documents
  match: "*"
upload_dir: img
public_path: "/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
