backend:

  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "img"

collections:

  - name: "special-pages"
    label: "Pages uniques"
    delete: false # Prevent users from deleting documents in this collection
    files:
      - name: "home"
        file: "index.md"
        label: "Éditer la page d'accueil"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "home"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "hidden", default: "/" }
          - {label: "Description", name: "description", widget: "string"}
          - {label: "Slogan 1", name: "slogan1", widget: "string", required: false}
          - {label: "Slogan 2", name: "slogan2", widget: "string", required: false}
          - {label: "Lien couverture", name: "cover_link", widget: "string", required: false}
          - {label: "Image de couverture", name: "cover_image", widget: "image"}
          - label: "Carrés"
            name: "square"
            widget: "list"
            fields:
              - {label: Titre du carré, name: name, widget: string}
              - {label: Lien du carré, name: link, widget: string}
              - {label: Description du carré, name: desc, widget: string}
              - {label: Description du lien, name: link_desc, widget: string}
              - {label: Image du carré, name: image, widget: image}

      - name: "produits"
        file: "produits.md"
        label: "Éditer la page des Produits"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "produits"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "hidden", default: "/produits" }
          - {label: "Description", name: "description", widget: "string"}
          - {label: "Slogan", name: "slogan", widget: "string", required: false}
          - {label: "Image de couverture", name: "cover_image", widget: "image"}
          - label: "Produits"
            name: "produits"
            widget: "list"
            fields:
              - {label: Image, name: image, widget: image}
              - {label: Nom, name: title, widget: string}
              - {label: Description, name: desc, widget: text}
              - {label: Ingrédients, name: ingredients, widget: markdown}
              - {label: Biologique?, name: bio, widget: boolean}
              - {label: Certifié Ecocert?, name: ecocert, widget: boolean}

      - name: "partenaires"
        file: "partenaires.md"
        label: "Éditer la page des Partenaires Locaux"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "produits"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "hidden", default: "/produits" }
          - {label: "Description", name: "description", widget: "string"}
          - {label: "Slogan", name: "slogan", widget: "string", required: false}
          - {label: "Image de couverture", name: "cover_image", widget: "image"}
          - {label: Texte introduction, name: body, widget: markdown, required:false}
          - label: "Partenaires"
            name: "partenaires"
            widget: "list"
            fields:
              - {label: Image, name: image, widget: image}
              - {label: Nom, name: title, widget: string}
              - {label: Description, name: desc, widget: text}

      - name: "points-de-vente"
        file: "points-de-vente.md"
        label: "Éditer la page des Points de Vente"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "produits"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "hidden", default: "/produits" }
          - {label: "Description", name: "description", widget: "string"}
          - {label: "Slogan", name: "slogan", widget: "string", required: false}
          - {label: "Image de couverture", name: "cover_image", widget: "image"}
          - label: "Points de vente"
            name: "locations"
            widget: "list"
            fields:
              - {label: Nom, name: title, widget: string}
              - {label: Addresse (Ligne 1), name: address_1, widget: string}
              - {label: Addresse (Ligne 2), name: address_2, widget: string}
              - {label: Lien vers site, name: url, widget: string}
              - {label: Texte pour lien vers site, name: url_text, widget: string}
              - {label: Latitude, name: lat, widget: string}
              - {label: Longitude, name: long, widget: string}

  - name: "settings"
    label: "Paramètres du site"
    delete: false # Prevent users from deleting documents in this collection
    editor:
     preview: false
    files:
       - name: "general"
         label: "Général"
         file: "_data/settings.yml"
         description: "Paramètres Généraux"
         fields:
           - {label: "Titre du site", name: "site_title", widget: "string"}
           - {label: "Courriel de contact", name: "site_email", widget: "string", required: false}
           - {label: "Numéro de téléphone de contact", name: "site_tel", widget: "string", required: false}
           - {label: "Lien vers page Facebook", name: "url_facebook", widget: "string", required: false}
           - {label: "Lien vers page Instagram", name: "url_instagram", widget: "string", required: false}
           - {label: "Lien vers page Twitter", name: "url_twitter", widget: "string", required: false}

       - name: "navigation"
         label: "Navigation"
         file: "_data/navigation.yml"
         description: "Navigation du site"
         fields:
          - label: "Liens navigation"
            name: main_nav
            widget: list
            required: false
            fields:
              - {label: Titre, name: title, widget: string}
              - {label: URL, name: url, widget: string}
